using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Entities.SocioNegocio
{
    public class ResponseBusinessPartners
    {
        public List<BusinessPartners> value { get; set; }
    }
    public class BusinessPartners
    {
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public int GroupCode { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string MailAddress { get; set; }
        public string MailZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Notes { get; set; }
        public int? PayTermsGrpCode { get; set; }
        public double? CreditLimit { get; set; }
        public double? MaxCommitment { get; set; }
        public double? DiscountPercent { get; set; }
        public string VatLiable { get; set; }
        public string FederalTaxId { get; set; }
        public string DeductibleAtSource { get; set; }
        public double? DeductionPercent { get; set; }
        public double? DeductionValidUntil { get; set; }
        public int? PriceListNum { get; set; }
        public double? IntrestRatePercent { get; set; }
        public double? CommissionPercent { get; set; }
        public double? CommissionGroupCode { get; set; }
        public string FreeText { get; set; }
        public int? SalesPersonCode { get; set; }
        public string Currency { get; set; }
        public string RateDiffAccount { get; set; }
        public string Cellular { get; set; }
        public string AvarageLate { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string MailCity { get; set; }
        public string MailCounty { get; set; }
        public string MailCountry { get; set; }
        public string EmailAddress { get; set; }
        public string Picture { get; set; }
        public string DefaultAccount { get; set; }
        public string DefaultBranch { get; set; }
        public double? DefaultBankCode { get; set; }
        public string AdditionalId { get; set; }
        public string Pager { get; set; }
        public string FatherCard { get; set; }
        public string CardForeignName { get; set; }
        public string FatherType { get; set; }
        public string DeductionOffice { get; set; }
        public string ExportCode { get; set; }
        public long MinIntrest { get; set; }
        public long CurrentAccountBalance { get; set; }
        public long OpenDeliveryNotesBalance { get; set; }
        public double? OpenOrdersBalance { get; set; }
        public long OpenChecksBalance { get; set; }
        public string VatGroup { get; set; }
        public string ShippingType { get; set; }
        public string Password { get; set; }
        public string Indicator { get; set; }
        public string Iban { get; set; }
        public long CreditCardCode { get; set; }
        public string CreditCardNum { get; set; }
        public string CreditCardExpiration { get; set; }
        public string DebitorAccount { get; set; }
        public string OpenOpportunities { get; set; }
        public string Valid { get; set; }
        public string ValidFrom { get; set; }
        public string ValidTo { get; set; }
        public string ValidRemarks { get; set; }
        public string Frozen { get; set; }
        public string FrozenFrom { get; set; }
        public string FrozenTo { get; set; }
        public string FrozenRemarks { get; set; }
        public string Block { get; set; }
        public string BillToState { get; set; }
        public string ShipToState { get; set; }
        public string ExemptNum { get; set; }
        public long Priority { get; set; }
        public string FormCode1099 { get; set; }
        public string Box1099 { get; set; }
        public string PeymentMethodCode { get; set; }
        public string BackOrder { get; set; }
        public string PartialDelivery { get; set; }
        public string BlockDunning { get; set; }
        public string BankCountry { get; set; }
        public string HouseBank { get; set; }
        public string HouseBankCountry { get; set; }
        public string HouseBankAccount { get; set; }
        public string ShipToDefault { get; set; }
        public string DunningLevel { get; set; }
        public string DunningDate { get; set; }
        public string CollectionAuthorization { get; set; }
        public string Dme { get; set; }
        public string InstructionKey { get; set; }
        public string SinglePayment { get; set; }
        public string IsrBillerId { get; set; }
        public string PaymentBlock { get; set; }
        public string ReferenceDetails { get; set; }
        public string HouseBankBranch { get; set; }
        public string OwnerIdNumber { get; set; }
        public long PaymentBlockDescription { get; set; }
        public string TaxExemptionLetterNum { get; set; }
        public long MaxAmountOfExemption { get; set; }
        public string ExemptionValidityDateFrom { get; set; }
        public string ExemptionValidityDateTo { get; set; }
        public string LinkedBusinessPartner { get; set; }
        public string LastMultiReconciliationNum { get; set; }
        public string DeferredTax { get; set; }
        public string Equalization { get; set; }
        public string SubjectToWithholdingTax { get; set; }
        public string CertificateNumber { get; set; }
        public string ExpirationDate { get; set; }
        public string NationalInsuranceNum { get; set; }
        public string AccrualCriteria { get; set; }
        public string WtCode { get; set; }
        public string BillToBuildingFloorRoom { get; set; }
        public string DownPaymentClearAct { get; set; }
        public string ChannelBp { get; set; }
        public string DefaultTechnician { get; set; }
        public string BilltoDefault { get; set; }
        public string CustomerBillofExchangDisc { get; set; }
        public string Territory { get; set; }
        public string ShipToBuildingFloorRoom { get; set; }
        public string CustomerBillofExchangPres { get; set; }
        public string ProjectCode { get; set; }
        public string VatGroupLatinAmerica { get; set; }
        public string DunningTerm { get; set; }
        public string Website { get; set; }
        public string OtherReceivablePayable { get; set; }
        public string BillofExchangeonCollection { get; set; }
        public string CompanyPrivate { get; set; }
        public long LanguageCode { get; set; }
        public string UnpaidBillofExchange { get; set; }
        public long WithholdingTaxDeductionGroup { get; set; }
        public string ClosingDateProcedureNumber { get; set; }
        public string Profession { get; set; }
        public string BankChargesAllocationCode { get; set; }
        public string TaxRoundingRule { get; set; }
        public string Properties1 { get; set; }
        public string Properties2 { get; set; }
        public string Properties3 { get; set; }
        public string Properties4 { get; set; }
        public string Properties5 { get; set; }
        public string Properties6 { get; set; }
        public string Properties7 { get; set; }
        public string Properties8 { get; set; }
        public string Properties9 { get; set; }
        public string Properties10 { get; set; }
        public string Properties11 { get; set; }
        public string Properties12 { get; set; }
        public string Properties13 { get; set; }
        public string Properties14 { get; set; }
        public string Properties15 { get; set; }
        public string Properties16 { get; set; }
        public string Properties17 { get; set; }
        public string Properties18 { get; set; }
        public string Properties19 { get; set; }
        public string Properties20 { get; set; }
        public string Properties21 { get; set; }
        public string Properties22 { get; set; }
        public string Properties23 { get; set; }
        public string Properties24 { get; set; }
        public string Properties25 { get; set; }
        public string Properties26 { get; set; }
        public string Properties27 { get; set; }
        public string Properties28 { get; set; }
        public string Properties29 { get; set; }
        public string Properties30 { get; set; }
        public string Properties31 { get; set; }
        public string Properties32 { get; set; }
        public string Properties33 { get; set; }
        public string Properties34 { get; set; }
        public string Properties35 { get; set; }
        public string Properties36 { get; set; }
        public string Properties37 { get; set; }
        public string Properties38 { get; set; }
        public string Properties39 { get; set; }
        public string Properties40 { get; set; }
        public string Properties41 { get; set; }
        public string Properties42 { get; set; }
        public string Properties43 { get; set; }
        public string Properties44 { get; set; }
        public string Properties45 { get; set; }
        public string Properties46 { get; set; }
        public string Properties47 { get; set; }
        public string Properties48 { get; set; }
        public string Properties49 { get; set; }
        public string Properties50 { get; set; }
        public string Properties51 { get; set; }
        public string Properties52 { get; set; }
        public string Properties53 { get; set; }
        public string Properties54 { get; set; }
        public string Properties55 { get; set; }
        public string Properties56 { get; set; }
        public string Properties57 { get; set; }
        public string Properties58 { get; set; }
        public string Properties59 { get; set; }
        public string Properties60 { get; set; }
        public string Properties61 { get; set; }
        public string Properties62 { get; set; }
        public string Properties63 { get; set; }
        public string Properties64 { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string VerificationNumber { get; set; }
        public string DiscountBasestring { get; set; }
        public string DiscountRelations { get; set; }
        public string TypeReport { get; set; }
        public string ThresholdOverlook { get; set; }
        public string SurchargeOverlook { get; set; }
        public string DownPaymentInterimAccount { get; set; }
        public string OperationCode347 { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string HierarchicalDeduction { get; set; }
        public string ShaamGroup { get; set; }
        public string WithholdingTaxCertified { get; set; }
        public string BookkeepingCertified { get; set; }
        public string PlanningGroup { get; set; }
        public string Affiliate { get; set; }
        public string Industry { get; set; }
        public string VatIdNum { get; set; }
        public string DatevAccount { get; set; }
        public string DatevFirstDataEntry { get; set; }
        public string UseShippedGoodsAccount { get; set; }
        public string GtsRegNo { get; set; }
        public string GtsBankAccountNo { get; set; }
        public string GtsBillingAddrTel { get; set; }
        public string ETaxWebSite { get; set; }
        public string HouseBankIban { get; set; }
        public string VatRegistrationNumber { get; set; }
        public string RepresentativeName { get; set; }
        public string IndustryType { get; set; }
        public string BusinessType { get; set; }
        public long Series { get; set; }
        public string AutomaticPosting { get; set; }
        public string InterestAccount { get; set; }
        public string FeeAccount { get; set; }
        public string CampaignNumber { get; set; }
        public string AliasName { get; set; }
        public string DefaultBlanketAgreementNumber { get; set; }
        public string EffectiveDiscount { get; set; }
        public string NoDiscounts { get; set; }
        public string EffectivePrice { get; set; }
        public string EffectivePriceConsidersPriceBeforeDiscount { get; set; }
        public string GlobalLocationNumber { get; set; }
        public string EdiSenderId { get; set; }
        public string EdiRecipientId { get; set; }
        public string ResidenNumber { get; set; }
        public string RelationshipCode { get; set; }
        public string RelationshipDateFrom { get; set; }
        public string RelationshipDateTill { get; set; }
        public string UnifiedFederalTaxId { get; set; }
        public string AttachmentEntry { get; set; }
        public string TypeOfOperation { get; set; }
        public string EndorsableChecksFromBp { get; set; }
        public string AcceptsEndorsedChecks { get; set; }
        public string OwnerCode { get; set; }
        public string BlockSendingMarketingContent { get; set; }
        public string AgentCode { get; set; }
        public string PriceMode { get; set; }
        public string EDocGenerationType { get; set; }
        public string EDocStreet { get; set; }
        public string EDocStreetNumber { get; set; }
        public string EDocBuildingNumber { get; set; }
        public string EDocZipCode { get; set; }
        public string EDocCity { get; set; }
        public string EDocCountry { get; set; }
        public string EDocDistrict { get; set; }
        public string EDocRepresentativeFirstName { get; set; }
        public string EDocRepresentativeSurname { get; set; }
        public string EDocRepresentativeCompany { get; set; }
        public string EDocRepresentativeFiscalCode { get; set; }
        public string EDocRepresentativeAdditionalId { get; set; }
        public string EDocPecAddress { get; set; }
        public string IpaCodeForPa { get; set; }
        public DateTimeOffset UpdateDate { get; set; }
        public DateTimeOffset UpdateTime { get; set; }
        public string ExemptionMaxAmountValidationType { get; set; }
        public string ECommerceMerchantId { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public DateTimeOffset CreateDate { get; set; }
        public DateTimeOffset CreateTime { get; set; }
        public string DefaultTransporterEntry { get; set; }
        public string DefaultTransporterLineNumber { get; set; }
        public string FceRelevant { get; set; }
        public string FceValidateBaseDelivery { get; set; }
        public string MainUsage { get; set; }
        public string EBooksVatExemptionCause { get; set; }
        public string LegalText { get; set; }
        public long DataVersion { get; set; }
        public string ExchangeRateForIncomingPayment { get; set; }
        public string ExchangeRateForOutgoingPayment { get; set; }
        public string CertificateDetails { get; set; }
        public string DefaultCurrency { get; set; }
        public string EoriNumber { get; set; }
        public string FceAsPaymentMeans { get; set; }
        public List<string> ElectronicProtocols { get; set; }
        public List<BPAddress> BpAddresses { get; set; }
        public List<ContactEmployee> ContactEmployees { get; set; }
        public List<string> BpAccountReceivablePaybleCollection { get; set; }
        public List<string> BpPaymentMethods { get; set; }
        public List<string> BpWithholdingTaxCollection { get; set; }
        public List<string> BpPaymentDates { get; set; }
        public List<string> BpBranchAssignment { get; set; }
        public List<string> BpBankAccounts { get; set; }
        public List<string> BpFiscalTaxIdCollection { get; set; }
        public List<string> DiscountGroups { get; set; }
        public BpIntrastatExtension BpIntrastatExtension { get; set; }
        public List<string> BpBlockSendingMarketingContents { get; set; }
        public List<string> BpCurrenciesCollection { get; set; }
    }

    public partial class BpIntrastatExtension
    {
    }
}
